spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.115.128:8848
    sentinel:
      transport:
        dashboard: 192.168.115.128:8080
        clientIp: 192.168.115.1
      filter:
        enabled: false
  application:
    name: provider
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: '*'
rocketmq:
  name-server: 192.168.115.128:9876
  producer:
    group: myProvider